# Stock Price Prediction using Linear Regression

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

sns.set()
%matplotlib inline

In [2]:
import quandl

In [3]:
#Authentication of Quandl Module using Quandl API key

quandl.ApiConfig.api_key = "kxdcGTXk2N_Nc6xp74Ep"

In [4]:
#Selecting Stock Prices of Apple Inc. using quandl code

df = quandl.get('EOD/AAPL')

In [5]:
df.head()

Open    High     Low    Close      Volume  Dividend  Split  \
Date                                                                       
2013-09-03  493.10  500.60  487.35  488.580  11854600.0       0.0    1.0   
2013-09-04  499.56  502.24  496.28  498.691  12322600.0       0.0    1.0   
2013-09-05  500.25  500.68  493.64  495.270   8441700.0       0.0    1.0   
2013-09-06  498.44  499.38  489.95  498.220  12840200.0       0.0    1.0   
2013-09-09  505.00  507.92  503.48  506.170  12167400.0       0.0    1.0   

             Adj_Open   Adj_High    Adj_Low  Adj_Close   Adj_Volume  
Date                                                                 
2013-09-03  15.619650  15.857223  15.437510  15.476472  331928800.0  
2013-09-04  15.824280  15.909173  15.720381  15.796753  345032800.0  
2013-09-05  15.846136  15.859757  15.636755  15.688388  236367600.0  
2013-09-06  15.788802  15.818578  15.519869  15.781833  359525600.0  
2013-09-09  15.996600  16.089095  15.948451  16.033661  340687200.0

In [6]:
df.tail()

Open     High      Low   Close      Volume  Dividend  Split  \
Date                                                                        
2017-12-21  174.17  176.020  174.100  175.01  20949896.0       0.0    1.0   
2017-12-22  174.68  175.424  174.500  175.01  16349444.0       0.0    1.0   
2017-12-26  170.80  171.470  169.679  170.57  33185536.0       0.0    1.0   
2017-12-27  170.10  170.780  169.710  170.60  21498213.0       0.0    1.0   
2017-12-28  171.00  171.850  170.480  171.08  16480187.0       0.0    1.0   

             Adj_Open   Adj_High    Adj_Low  Adj_Close   Adj_Volume  
Date                                                                 
2017-12-21  41.899570  42.344619  41.882730  42.101646   83799584.0  
2017-12-22  42.022259  42.201241  41.978957  42.101646   65397776.0  
2017-12-26  41.088858  41.250038  40.819183  41.033528  132742144.0  
2017-12-27  40.920461  41.084047  40.826640  41.040745   85992852.0  
2017-12-28  41.136972  41.341454  41.011877  41.156217   65920748.0

In [7]:
df.shape

(1090, 12)

**Adding Two New Columns**

In [8]:
# adding high low percentage column

df['HL_PCT'] = (df['Adj_High'] - df['Adj_Low']) / df['Adj_Close'] * 100.0

In [9]:
# adding percentage column

df['PCT_change'] = (df['Adj_Close'] - df['Adj_Open']) / df['Adj_Open'] * 100.0

In [10]:
df.head()

Open    High     Low    Close      Volume  Dividend  Split  \
Date                                                                       
2013-09-03  493.10  500.60  487.35  488.580  11854600.0       0.0    1.0   
2013-09-04  499.56  502.24  496.28  498.691  12322600.0       0.0    1.0   
2013-09-05  500.25  500.68  493.64  495.270   8441700.0       0.0    1.0   
2013-09-06  498.44  499.38  489.95  498.220  12840200.0       0.0    1.0   
2013-09-09  505.00  507.92  503.48  506.170  12167400.0       0.0    1.0   

             Adj_Open   Adj_High    Adj_Low  Adj_Close   Adj_Volume    HL_PCT  \
Date                                                                            
2013-09-03  15.619650  15.857223  15.437510  15.476472  331928800.0  2.711941   
2013-09-04  15.824280  15.909173  15.720381  15.796753  345032800.0  1.195129   
2013-09-05  15.846136  15.859757  15.636755  15.688388  236367600.0  1.421447   
2013-09-06  15.788802  15.818578  15.519869  15.781833  359525600.0  1.892738   
2013-09-09  15.996600  16.089095  15.948451  16.033661  340687200.0  0.877176   

            PCT_change  
Date                    
2013-09-03   -0.916650  
2013-09-04   -0.173953  
2013-09-05   -0.995502  
2013-09-06   -0.044138  
2013-09-09    0.231683

In [11]:
df.shape

(1090, 14)

In [12]:
df.describe()

Open         High          Low        Close        Volume  \
count  1090.000000  1090.000000  1090.000000  1090.000000  1.090000e+03   
mean    194.564537   196.114735   193.016676   194.613130  3.605114e+07   
std     160.562848   161.812898   159.407381   160.647536  2.194473e+07   
min      90.000000    90.700000    89.470000    90.280000  5.704900e+06   
25%     108.042500   108.942500   106.972500   108.007500  2.120714e+07   
50%     121.585000   122.504950   120.640000   121.755000  3.248325e+07   
75%     156.905000   157.809625   155.744975   156.515000  4.673778e+07   
max     649.900000   651.260000   644.470000   647.350000  1.895606e+08   

          Dividend        Split     Adj_Open     Adj_High      Adj_Low  \
count  1090.000000  1090.000000  1090.000000  1090.000000  1090.000000   
mean      0.015642     1.005505    26.367551    26.578236    26.152043   
std       0.175122     0.181735     6.614490     6.640870     6.578682   
min       0.000000     1.000000    14.189776    14.561974    14.166335   
25%       0.000000     1.000000    22.170235    22.433992    21.948836   
50%       0.000000     1.000000    25.781510    26.055842    25.511496   
75%       0.000000     1.000000    29.329099    29.541994    29.133958   
max       3.290000     7.000000    42.125703    42.628488    42.065561   

         Adj_Close    Adj_Volume       HL_PCT   PCT_change  
count  1090.000000  1.090000e+03  1090.000000  1090.000000  
mean     26.373196  1.931334e+08     1.649472     0.026796  
std       6.616455  1.112891e+08     0.972525     1.147303  
min      14.258197  4.590369e+07     0.438218    -6.633066  
25%      22.201030  1.133450e+08     1.033811    -0.603549  
50%      25.789823  1.681963e+08     1.456946     0.046380  
75%      29.362853  2.394642e+08     1.965879     0.705480  
max      42.440845  1.065523e+09    16.291699     8.696110

In [13]:
# Creating a new dataframe of important columns

df_imp = df[['Adj_Close', 'Adj_Volume', 'HL_PCT', 'PCT_change']]

In [14]:
df_imp.head()

Adj_Close   Adj_Volume    HL_PCT  PCT_change
Date                                                    
2013-09-03  15.476472  331928800.0  2.711941   -0.916650
2013-09-04  15.796753  345032800.0  1.195129   -0.173953
2013-09-05  15.688388  236367600.0  1.421447   -0.995502
2013-09-06  15.781833  359525600.0  1.892738   -0.044138
2013-09-09  16.033661  340687200.0  0.877176    0.231683

In [15]:
# checking for null values in new dataframe

df_imp.isnull().sum()

Adj_Close     0
Adj_Volume    0
HL_PCT        0
PCT_change    0
dtype: int64

In [16]:
# generating prediction for every day for the next 10 days

df_imp['Prediction'] = df_imp[['Adj_Close']].shift(-10)

In [17]:
df_imp.head()

Adj_Close   Adj_Volume    HL_PCT  PCT_change  Prediction
Date                                                                
2013-09-03  15.476472  331928800.0  2.711941   -0.916650   14.422914
2013-09-04  15.796753  345032800.0  1.195129   -0.173953   14.719406
2013-09-05  15.688388  236367600.0  1.421447   -0.995502   14.960780
2013-09-06  15.781833  359525600.0  1.892738   -0.044138   14.805882
2013-09-09  16.033661  340687200.0  0.877176    0.231683   15.541726

In [18]:
df_imp.tail()

Adj_Close   Adj_Volume    HL_PCT  PCT_change  Prediction
Date                                                                
2017-12-21  42.101646   83799584.0  1.097080    0.482287         NaN
2017-12-22  42.101646   65397776.0  0.527970    0.188917         NaN
2017-12-26  41.033528  132742144.0  1.050009   -0.134660         NaN
2017-12-27  41.040745   85992852.0  0.627198    0.293945         NaN
2017-12-28  41.156217   65920748.0  0.800795    0.046784         NaN

In [19]:
# checking for null values 

df_imp.isnull().sum()

Adj_Close      0
Adj_Volume     0
HL_PCT         0
PCT_change     0
Prediction    10
dtype: int64

In [20]:
# removing null values

df_imp.dropna(axis = 0, inplace = True)

In [21]:
df_imp.head()

Adj_Close   Adj_Volume    HL_PCT  PCT_change  Prediction
Date                                                                
2013-09-03  15.476472  331928800.0  2.711941   -0.916650   14.422914
2013-09-04  15.796753  345032800.0  1.195129   -0.173953   14.719406
2013-09-05  15.688388  236367600.0  1.421447   -0.995502   14.960780
2013-09-06  15.781833  359525600.0  1.892738   -0.044138   14.805882
2013-09-09  16.033661  340687200.0  0.877176    0.231683   15.541726

In [22]:
df_imp.tail()

Adj_Close   Adj_Volume    HL_PCT  PCT_change  Prediction
Date                                                                
2017-12-07  40.732819  102693232.0  0.903614    0.171567   42.101646
2017-12-08  40.744848   93420924.0  1.287123   -0.656930   42.101646
2017-12-11  41.538719  141095036.0  2.374472    2.050827   41.033528
2017-12-12  41.305369   77636920.0  0.541060   -0.261400   41.040745
2017-12-13  41.442492   95273788.0  0.893946   -0.133333   41.156217

In [23]:
df_imp.isnull().sum()

Adj_Close     0
Adj_Volume    0
HL_PCT        0
PCT_change    0
Prediction    0
dtype: int64

In [24]:
# Creating X and y dataframes

X = df_imp.iloc[:, :-1].values
y = df_imp.iloc[:, -1].values

In [25]:
X

array([[ 1.54764725e+01,  3.31928800e+08,  2.71194073e+00,
        -9.16649767e-01],
       [ 1.57967529e+01,  3.45032800e+08,  1.19512885e+00,
        -1.73953079e-01],
       [ 1.56883878e+01,  2.36367600e+08,  1.42144689e+00,
        -9.95502249e-01],
       ...,
       [ 4.15387189e+01,  1.41095036e+08,  2.37447154e+00,
         2.05082742e+00],
       [ 4.13053688e+01,  7.76369200e+07,  5.41059988e-01,
        -2.61399942e-01],
       [ 4.14424921e+01,  9.52737880e+07,  8.93945551e-01,
        -1.33333333e-01]])

In [26]:
y

array([14.42291424, 14.71940567, 14.96078011, ..., 41.03352802,
       41.04074503, 41.15621723])

In [27]:
X.shape, y.shape

((1080, 4), (1080,))

In [28]:
# splitting the data into training and testing data

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)

In [29]:
X_train[:5], X_test[:5]

(array([[ 1.88725345e+01,  2.91597600e+08,  1.01102823e+00,
          1.71502378e-01],
        [ 2.31517784e+01,  1.26851744e+08,  8.75948599e-01,
          3.04475794e-01],
        [ 2.55209308e+01,  1.69457312e+08,  1.55961609e+00,
          4.91514421e-01],
        [ 2.67503444e+01,  1.88092184e+08,  2.57967952e+00,
         -1.39769077e+00],
        [ 2.19276165e+01,  3.71672000e+08,  2.78835271e+00,
          1.85495703e+00]]),
 array([[ 3.04258946e+01,  1.82383888e+08,  1.18454806e+00,
          7.14285714e-01],
        [ 2.57234779e+01,  1.01423904e+08,  9.43050723e-01,
          1.09990834e-01],
        [ 3.00149821e+01,  3.07025708e+08,  1.98852772e+00,
         -1.58073015e+00],
        [ 1.70629443e+01,  2.00062800e+08,  1.05567661e+00,
          2.71227304e-01],
        [ 2.24127191e+01,  1.56083932e+08,  2.90774984e+00,
         -2.61027924e+00]]))

In [30]:
y_train[:5], y_test[:5]

(array([19.793934  , 21.87975414, 26.74327885, 26.50069341, 21.42449288]),
 array([29.33777978, 24.98865598, 26.31676897, 17.02768759, 23.63277567]))

In [31]:
X_train.shape, X_test.shape

((810, 4), (270, 4))

In [32]:
y_train.shape, y_test.shape

((810,), (270,))

In [33]:
# from sklearn.preprocessing import MinMaxScaler

# norm = MinMaxScaler()
# X_train = norm.fit_transform(X_train)
# X_test = norm.transform(X_test)

In [34]:
X_train[:5]

array([[ 1.88725345e+01,  2.91597600e+08,  1.01102823e+00,
         1.71502378e-01],
       [ 2.31517784e+01,  1.26851744e+08,  8.75948599e-01,
         3.04475794e-01],
       [ 2.55209308e+01,  1.69457312e+08,  1.55961609e+00,
         4.91514421e-01],
       [ 2.67503444e+01,  1.88092184e+08,  2.57967952e+00,
        -1.39769077e+00],
       [ 2.19276165e+01,  3.71672000e+08,  2.78835271e+00,
         1.85495703e+00]])

In [35]:
X_test[:5]

array([[ 3.04258946e+01,  1.82383888e+08,  1.18454806e+00,
         7.14285714e-01],
       [ 2.57234779e+01,  1.01423904e+08,  9.43050723e-01,
         1.09990834e-01],
       [ 3.00149821e+01,  3.07025708e+08,  1.98852772e+00,
        -1.58073015e+00],
       [ 1.70629443e+01,  2.00062800e+08,  1.05567661e+00,
         2.71227304e-01],
       [ 2.24127191e+01,  1.56083932e+08,  2.90774984e+00,
        -2.61027924e+00]])

In [36]:
X_train.shape, X_test.shape

((810, 4), (270, 4))

In [37]:
# fitting training data to the model

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [38]:
# training and testing score of our model

training_score = model.score(X_train, y_train) 
print(f"Training Score of our Linear Regression Model is {round(training_score*100, 2)} %")

testing_score = model.score(X_test, y_test)
print(f"Testing Score of our Linear Regression Model is {round(testing_score*100, 2)} %")

Training Score of our Linear Regression Model is 96.95 %
Testing Score of our Linear Regression Model is 96.81 %


### Model Prediction

In [39]:
y_pred = model.predict(X_test)
y_pred[:10]

array([30.6962176 , 26.02274261, 30.28989397, 17.31892211, 22.77006453,
       17.61625734, 16.7972188 , 22.07532219, 17.31475634, 26.82436799])

In [40]:
# Comparing Actual values with predicted values

comp = pd.DataFrame({"Actual Price": y_test, "Predicted Price": y_pred})
comp.head(10)

Actual Price  Predicted Price
0     29.337780        30.696218
1     24.988656        26.022743
2     26.316769        30.289894
3     17.027688        17.318922
4     23.632776        22.770065
5     16.656531        17.616257
6     16.687352        16.797219
7     24.256466        22.075322
8     17.024803        17.314756
9     25.545528        26.824368

### Model Evaluation

In [41]:
# Calculating accuracy of our model

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

accuracy = r2_score(y_test, y_pred)
print(f"Accuracy Score of our model is : {round(accuracy*100, 2)} %")

mse = mean_squared_error(y_test, y_pred)
print(f"Accuracy Score of our model is : {mse}")

mae = mean_absolute_error(y_test, y_pred)
print(f"Accuracy Score of our model is : {mae}")

Accuracy Score of our model is : 96.81 %
Accuracy Score of our model is : 1.360290480855569
Accuracy Score of our model is : 0.890209467813388


### Price Prediction Function

In [42]:
def Predict_price(days):
    
    n = days
    
    df_imp['Prediction'] = df_imp[['Adj_Close']].shift(-n)
    
    df_imp.dropna(axis = 0, inplace = True)
    
    X = df_imp.iloc[:, :-1].values
    y = df_imp.iloc[:, -1].values
    
    X = X[:-n]
    y = y[:-n]
    
    # splitting data into training and testing dataset
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)
    
    # scaling our data
    
#     norm = MinMaxScaler()
#     X_train = norm.fit_transform(X_train)
#     X_test = norm.transform(X_test)
    
    model = LinearRegression()
    model.fit(X_train, y_train)
    
    training_score = model.score(X_train, y_train) 
    print(f"Training Score of our Linear Regression Model is {round(training_score*100, 2)} % \n")

    testing_score = model.score(X_test, y_test)
    print(f"Testing Score of our Linear Regression Model is {round(testing_score*100, 2)} % \n")
    
    y_pred = model.predict(X_test)
    accuracy = r2_score(y_test, y_pred)
    print(f"Accuracy Score of Model is : {round(accuracy*100, 2)} % \n")
    
    # set x_forecast equal to last 10 rows of the original data set from Adj_close column
    X_forecast = np.array(df_imp.drop(['Prediction'],1))[-n:]
    
    # print linear regression model prediction for next 'n' days
    lr_prediction = model.predict(X_forecast)
    print('Prediction for next {} day price:\n\n{}'.format(n,lr_prediction))

In [43]:
# Predicted price for next 6 days
Predict_price(6)

Training Score of our Linear Regression Model is 98.01 % 

Testing Score of our Linear Regression Model is 98.05 % 

Accuracy Score of Model is : 98.05 % 

Prediction for next 6 day price:

[41.80807541 41.10028794 41.44180774 41.24758806 41.08291235 40.9188596 ]


In [44]:
# Predicted price for next 10 days
Predict_price(10)

Training Score of our Linear Regression Model is 96.61 % 

Testing Score of our Linear Regression Model is 96.16 % 

Accuracy Score of Model is : 96.16 % 

Prediction for next 10 day price:

[42.14424027 42.48050759 42.40194908 42.27237049 42.10517301 41.49463727
 40.93584754 41.41649816 41.20109879 41.15719071]


In [45]:
# Predicted price for next 1 day
Predict_price(1)

Training Score of our Linear Regression Model is 99.66 % 

Testing Score of our Linear Regression Model is 99.65 % 

Accuracy Score of Model is : 99.65 % 

Prediction for next 1 day price:

[40.94653074]


In [46]:
# Predicted price for next 15 days
Predict_price(15)

Training Score of our Linear Regression Model is 94.67 % 

Testing Score of our Linear Regression Model is 94.31 % 

Accuracy Score of Model is : 94.31 % 

Prediction for next 15 day price:

[37.50547186 37.59916241 37.6575132  37.56754153 37.7522022  38.42325449
 38.57673719 38.42396643 37.46286616 37.59518787 37.60999488 37.77714273
 37.66968607 37.85648142 39.1419799 ]
